export const ADD_FORM_ELEMENT = "ADD_FORM_ELEMENT"
export const REMOVE_FORM_ELEMENT = "REMOVE_FORM_ELEMENT"
export const EDIT_FORM_ELEMENT = "EDIT_FORM_ELEMENT"
export const EDIT_ELEMENT = "EDIT_ELEMENT"